version: '2'
services:
    fireflycasemanageradmin-app:
        image: fireflycasemanageradmin
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://fireflycasemanageradmin-postgresql:5432/FireFlyCaseManagerAdmin
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fireflycasemanageradmin-postgresql:
        extends:
            file: postgresql.yml
            service: fireflycasemanageradmin-postgresql
